### ISSUE TITLE
[Streamable] Don't use a config file

### ISSUE THREAD

**Issue by rfornea** [oysterprotocol/oyster-streamable#19]
Oyster-streamable has a config file with a specific address for downloading.  This is inconvenient for testing/QAing, since you have to go into the node_modules and change that address to some different brokernode.  Ideally, oyster-streamable shouldn't have a config--it would just use the config values from whatever project is consuming streamable.

**Comment by CKH4** [comment]
I'll do this. It will be a required option when you create a new Download object. This will be in line with how it is handled in the Upload.
