### ISSUE TITLE
[Streamable] Use datamap-generator lib

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/oyster-streamable#5]
A lot of the encryption and datamap functions are duplicated. We should be DRY so we can focus on only optimizing just 1 module.

**Comment by jfarago** [comment]
@AaronVasquez would this be a good time to rename the datamap-generator to be more of a utility library?

**Comment by AaronVasquez** [comment]
Hm, utils might be too vague. What name were you thinking of?

**Comment by jfarago** [comment]
Oh man... here we go, let me get back to you in a week. 🤣

**Comment by rfornea** [comment]
oysterUtils?  oysterShared?

**Comment by AaronVasquez** [comment]
Do want this to be a dumping ground of shared things? Or something more focused?

If it's just a dumping ground, oyster-utils could probably work.

**Comment by rfornea** [comment]
My personal preference is a dumping ground of shared things.  My reason is that I don't want us to have to maintain a different repo for everything we want to share.

**Comment by AaronVasquez** [comment]
sgtm. oyster-utils it is
